; ─── Docgen: an HTML documentation DSL embedded in rlisp ───
; Run:  rlisp run examples/docgen.lisp

; ─── String helper ─────────────────────────────────────────
; s → String::from — convert a &str literal to a String.
; Use for string arguments to functions that take String params.

(defmacro s (text)
  (quasiquote (String::from (unquote text))))

; ─── HTML element functions ────────────────────────────────
; Body/content params take String (may come from other functions or format!).
; Heading/label params take &str (always string literals).

(fn page-header ((title &str) (subtitle &str)) String
  (format! "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>{}</title><style>body{{font-family:system-ui,-apple-system,sans-serif;max-width:48rem;margin:0 auto;padding:2rem 1.5rem;color:#1a1a1a;line-height:1.6;background:#fafafa}}header{{margin-bottom:2.5rem;padding-bottom:1.5rem;border-bottom:2px solid #e0e0e0}}h1{{font-size:2.2rem;margin:0 0 .25rem;color:#111}}.subtitle{{font-size:1.1rem;color:#555;margin:0}}h2{{font-size:1.5rem;margin:2rem 0 .75rem;color:#222;border-bottom:1px solid #eee;padding-bottom:.35rem}}p{{margin:.6rem 0}}ul{{margin:.5rem 0;padding-left:1.5rem}}li{{margin:.25rem 0}}pre{{background:#f0f0f0;border:1px solid #ddd;border-radius:6px;padding:1rem;overflow-x:auto;font-size:.9rem;line-height:1.45}}code{{font-family:'SF Mono',Fira Code,monospace;font-size:.88em}}p code,li code{{background:#eee;padding:.1em .35em;border-radius:3px}}.note{{padding:.75rem 1rem;margin:1rem 0;border-radius:6px;border-left:4px solid}}.note.info{{background:#e8f4fd;border-color:#2196f3}}.note.warn{{background:#fff8e1;border-color:#ff9800}}.note.tip{{background:#e8f5e9;border-color:#4caf50}}.rule-box{{margin-bottom:1.25rem}}</style></head><body><main class=\"doc-page\"><header><h1>{}</h1><p class=\"subtitle\">{}</p></header>"
    title title subtitle))

(fn page-footer () String
  (format! "<footer>Generated by <strong>docgen</strong> — an rlisp documentation DSL</footer></main></body></html>"))

(fn section-html ((heading &str) (body String)) String
  (format! "<section><h2>{}</h2><div class=\"section-body\">{}</div></section>" heading body))

(fn text-html ((content &str)) String
  (format! "<p>{}</p>" content))

(fn list-html ((items String)) String
  (format! "<ul>{}</ul>" items))

(fn list-item ((content String)) String
  (format! "<li>{}</li>" content))

(fn code-block ((lang &str) (code &str)) String
  (format! "<pre><code class=\"language-{}\">{}</code></pre>" lang code))

(fn inline-code ((code &str)) String
  (format! "<code>{}</code>" code))

(fn rule-box ((label &str) (body &str)) String
  (format! "<div class=\"rule\"><div class=\"rule-label\">{}</div><p class=\"rule-body\">{}</p></div>" label body))

(fn note-html ((kind &str) (body &str)) String
  (format! "<div class=\"note {}\"><div class=\"note-label\">{}</div><p>{}</p></div>" kind kind body))

; ─── Page: Ownership Guide ─────────────────────────────────

(fn ownership-guide () String
  (format! "{}{}{}{}{}"
    (page-header "Ownership" "Move semantics and borrow inference without annotations.")

    (section-html "Three Rules"
      (format! "{}{}{}{}{}"
        (text-html "Loon's ownership system keeps memory safe without a garbage collector, and it boils down to three rules. If you internalize these, everything else follows.")
        (rule-box "Rule 1" "Every value has exactly one owner at any given time.")
        (rule-box "Rule 2" "When the owner goes out of scope, the value is automatically dropped — no use-after-free, no double-free.")
        (rule-box "Rule 3" "You can borrow a value through references, but mutable borrows are exclusive: many readers or one writer, never both.")
        (note-html "tip" "Think of ownership like a book from a library: only one person can check it out (own it), others can photocopy pages (borrow), but only the holder can write in the margins (mutably borrow).")))

    (section-html "Moves and Copies"
      (format! "{}{}{}{}{}"
        (text-html "Assignment and argument passing are moves by default. The original binding becomes inaccessible, preventing accidental sharing.")
        (code-block "loon"
          "(let a \"hello\")\n(let b a)       ; a moved, b owns it now\n(println! \"{}\" b)  ; fine\n; (println! \"{}\" a) ; compile error: use of moved value")
        (format! "<p>Types that implement {} — like integers, booleans, and small fixed-size types — are copied instead of moved. You can keep using the original.</p>"
          (inline-code "Copy"))
        (format! "<p>If a type implements {}, you can explicitly request a deep copy with {}.</p>"
          (inline-code "Clone") (inline-code ".clone()"))
        (note-html "info" "Moves are zero-cost at runtime — the compiler just forbids access to the old binding. No refcounting, no GC tracing.")))

    (section-html "Borrows and References"
      (format! "{}{}{}{}{}"
        (text-html "Instead of transferring ownership, you can lend a value by creating a reference:")
        (code-block "loon"
          "(fn print-length ((s &String)) ()\n  (println! \"length: {}\" (s.len)))\n\n(fn main () ()\n  (let text (String::from \"hello\"))\n  (print-length (& text))  ; lend it\n  (println! \"{}\" text))  ; we can still use it")
        (text-html "Loon enforces these rules at compile time — no runtime overhead, no garbage collector pauses, no reference counting.")
        (format! "<p>The shared borrow ({}) allows many simultaneous readers. The mutable borrow ({}) is exclusive: exactly one writer at a time, and no readers while writing.</p>"
          (inline-code "&T") (inline-code "&mut T"))
        (note-html "info" "The borrow checker can feel pedantic at first, but it almost always catches real bugs. If it compiles, your program is free of data races, use-after-free, and iterator invalidation — guarantees even seasoned C++ developers cannot make.")))

    (page-footer)))

; ─── Page: Traits and Generics ─────────────────────────────

(fn traits-guide () String
  (format! "{}{}{}{}{}"
    (page-header "Traits and Generics" "Polymorphism without inheritance.")

    (section-html "Traits Are Contracts"
      (format! "{}{}{}"
        (text-html "A trait defines behavior that types can implement. It's like an interface in Java or a typeclass in Haskell — but resolved statically at compile time.")
        (code-block "loon"
          "(trait Summary (\n  (fn summarize ((&self)) String)\n  (fn author ((&self)) String \"Anonymous\")))  ; default impl")
        (text-html "Implementing a trait is separate from the type definition — you can implement your traits for any type, including types from other crates (the \"orphan rule\" applies).")))

    (section-html "Generics and Constraints"
      (format! "{}{}{}"
        (text-html "Generic functions use angle brackets for type parameters and inline trait bounds:")
        (code-block "loon"
          "(fn largest (generic T) ((list &[T])) &T\n  where T: (PartialOrd)\n  (let largest-ref (& ([] list 0)))\n  (for (item list)\n    (if (> item largest-ref)\n      (largest-ref (& item))))\n  largest-ref)")
        (format! "<p>The {} introduces a type parameter, and {} constrains it. Multiple bounds use the {} operator: {}.</p>"
          (inline-code "(generic T)")
          (inline-code "where T: (PartialOrd)")
          (inline-code "+")
          (inline-code "(TraitA + TraitB)"))))

    (section-html "Common Traits"
      (format! "{}{}{}"
        (text-html "Loon's standard library revolves around a handful of key traits:")
        (list-html
          (format! "{}{}{}{}{}"
            (list-item (format! "{} — pretty-printing for developers" (inline-code "Debug")))
            (list-item (format! "{} — user-facing formatting"    (inline-code "Display")))
            (list-item (format! "{} — explicit deep copy"         (inline-code "Clone")))
            (list-item (format! "{} — trivial bitwise copy (integers, bools, etc.)" (inline-code "Copy")))
            (list-item (format! "{} — ordering and sorting"       (inline-code "PartialOrd / Ord")))))
        (format! "<div class=\"note tip\"><div class=\"note-label\">tip</div><p>Most of these can be auto-derived. In Loon, just include them in the type definition: {}.</p></div>"
          (inline-code "(struct Point (x f64) (y f64) derive(Debug Clone))"))))

    (page-footer)))

; ─── Main ──────────────────────────────────────────────────

(fn main () ()
  (println! "{}" (ownership-guide))
  (println! "{}" (traits-guide)))
